services:
  usermanagement:
    image: usermanagement
    build:
      context: .
      dockerfile: UserManagement/Dockerfile

  productmanagement:
    image: productmanagement
    build:
      context: .
      dockerfile: ProductManagement/Dockerfile

  productmanagement.presentation:
    image: productmanagement.presentation
    build:
      context: .
      dockerfile: ProductManagement/ProductManagement.Presentation/Dockerfile

  usermanagement.presentation:
    image: usermanagement.presentation
    build:
      context: .
      dockerfile: UserManagement/UserManagement.Presentation/Dockerfile
