services:
  productmanagement:
    image: products:shop
    build:
      context: ./ProductManagement
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=2000
    depends_on:
      - db

  usermanagement:
    image: users:shop
    build:
      context: ./UserManagement
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=3000
    depends_on:
      - db

  db:
    container_name: postgres_shop
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8653
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
