services:
  usermanagement:
    image: usermanagement
    build:
      context: .
      dockerfile: UserManagement/Dockerfile

  productmanagement:
    image: productmanagement
    build:
      context: .
      dockerfile: ProductManagement/Dockerfile
