FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["ProductManagement/ProductManagement.Presentation/ProductManagement.Presentation.csproj", "ProductManagement/ProductManagement.Presentation/"]
RUN dotnet restore "ProductManagement/ProductManagement.Presentation/ProductManagement.Presentation.csproj"
COPY . .
WORKDIR "/src/ProductManagement/ProductManagement.Presentation"
RUN dotnet build "ProductManagement.Presentation.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "ProductManagement.Presentation.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ProductManagement.Presentation.dll"]
